version: '3.9'

services:
    rabbit:
        hostname: rabbit
        image: 'rabbitmq:3-management'
        environment:
            - RABBITMQ_DEFAULT_USER=${CELERY_BROKER_USER}
            - RABBITMQ_DEFAULT_PASS=${CELERY_BROKER_PASSWORD}
        ports:
            - '15672:15672'
            - '5672:5672'
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data/
        environment:
            - POSTGRES_HOST=${DATABASE_HOST}
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_PORT=${DATABASE_PORT}
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - '8000:8000'
        depends_on:
            - db
            - rabbit
