# Generated by Django 4.0 on 2022-01-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_cv_options_cv_about_cv_education_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='experience_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
