# Generated by Django 4.0 on 2022-01-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_cv_experience_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='about',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
