# Generated by Django 4.0 on 2022-01-02 12:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_alter_cv_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=10),
        ),
    ]
