# Generated by Django 4.0 on 2022-01-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_cv_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='cv_file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
